spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/NapManiac/SpringConfigTest
#          username: 1394327107@qq.com
#          password:
#          search-paths:
#      label: master
server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 刷新配置
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

